version: '3.8'

services:
  react-app:
    container_name: job-finder-app
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/app/src
    ports:
      - '3000:3000'
    environment:
      - WATCHPACK_POLLING=true
      - SKIP_PREFLIGHT_CHECK=true
